region = "eu-west-2"
access_key = ""
secret_key = ""
block-range = "172.31.0.0/16"
vpc="Test-VPC"
subnet="Test-subnet"
tenancy="default"
sg-description="Allow TLS inbound traffic"
sg-name="Test-SG"
frport="0"
toport="0"
protocol="-1"
sgblock-range= ["0.0.0.0/0"]
ingress-description =" allows all traffic"
lcname="Testing Launch Configuration"
imageid="ami-032598fcc7e9d1c7a"
type="t2.micro"
asggroup="testing-Auto-scale-group"
desired_capacity=1
min=1
max=10
